# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  
  #config.vm.network "private_network", type: "dhcp"
  #config.vm.synced_folder "../../src", "/home/vagrant/src", type: "nfs"

  config.vm.define :nox do |box|
    
    box.vm.box = "precise64"
    box.vm.box_url = "http://files.vagrantup.com/precise64.box"

    box.vm.provision :puppet do |puppet|
      puppet.manifests_path = "puppetmanifests"
      puppet.manifest_file = "raspberry-nox.pp"
      puppet.module_path = "modules"
      puppet.options = ["--verbose", "--debug"]
    end
  end
  
end
